import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import "@assets/main.css";
import "@assets/chrome-bug.css";
import Layout from "@/app/components/common/Layout";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";
//import { getSession } from "@/auth"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {/* <Layout>{children}</Layout> */}
          <Layout>
            <Suspense>
              <main>{children}</main>
            </Suspense>
          </Layout>
        </SessionProvider>
      </body>
    </html>
  );
}
